@startuml

actor "Responsable pédagogique" as RP
participant "WebCand" as WC
actor "Candidat admis" as CA

RP -> WC : Organiser une session de recrutement
activate WC #Gold

RP -> WC : Nommer un tuteur de formation

RP -> WC : Visualiser le tableau de bord
activate WC #Orange
WC --> RP : Afficher le tableau de bord
activate RP #Orange
RP -> WC : Afficher les statistiques des candidats
WC --> RP : Afficher les statistiques des candidats
deactivate WC


RP -> WC : Consulter les candidatures
activate WC #GreenYellow
WC --> RP : Afficher les candidatures
deactivate WC
activate RP #GreenYellow
RP -> WC : Consulter le dossier d'un candidat
deactivate RP
activate WC #OrangeRed

WC --> RP : Afficher le dossier d'un candidat

activate RP #OrangeRed
RP -> WC : Consulter la vidéo du candidat
WC --> RP : Afficher la vidéo du candidat
RP -> WC : Consulter le CV du candidat
WC --> RP : Afficher le CV du candidat
RP -> WC : Consulter la lettre de motivation du candidat
WC --> RP : Afficher la lettre de motivation du candidat
RP -> WC : Valider la candidature
deactivate RP
WC -> CA : Envoyer un mail d'admissibilité
deactivate WC



@enduml